# This is a basic workflow to help you get started with Actions

name: AWS Resource Shutdown
env:
  EC2_TAGS: Environment:Development
  AWS_REGION: ${{ secrets.AWS_REGION }}
  DB_NAMES: ""

# events run 6am UTC
on:
  schedule:
  - cron: "0 6 * * *"
    
jobs:
  deploy:
    name: Shutdown AWS Resources
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: EC2 Shutdown
      run: |
        chmod +x ./script/ec2.sh
        ./script/ec2.sh stop ${EC2_TAGS}

    - name: RDS Shutdown
      run: |
        chmod +x ./script/rds.sh
        ./script/rds.sh stop ${DB_NAMES}
